### ISSUE TITLE
Allow variable path for config data folder

### ISSUE THREAD

**Issue by JyeGuru** [AriAlavi/rimlink#2]
Rimworld can be run with the `-savedatafolder=` parameter, which allows for a portable Rimworld installation. This is most useful when playing multiple different multiplayer games with various friends, where a simple launch script can point the config to a new folder (and thus loading a different set of mods) for each game.

Unfortunately, it seems that RimLink has a hard-coded path for the location of the config files - the default location. Would it be possible to allow this path to be passed with an argument to allow for portable usage?

**Comment by AriAlavi** [comment]
Yes, it's possible. Currently, the config folder is hardcoded in "rimlink.py"  line 100. It would need to be done through a global variable, as the method in question is static. If the global variable is not null, it could use the path of the global variable instead. The global variable could be set by argv in main.main()

**Comment by JyeGuru** [comment]
Added to my to-do list when I get some time over the next couple of weeks. Should be easy enough to check the global in `getRimworldConfigArea()`: https://github.com/AriAlavi/rimlink/blob/master/rimlink.py#L97-L100

**Comment by Coffee-fueled-deadlines** [comment]
@JyeGuru added a Pull request that should resolve this issue.
